### ISSUE TITLE
import conflict in training notebook

### ISSUE THREAD

**Issue by dluke** [turleyjm/cell-division-dl-plugin#1]
IPython notebooks for training have the following two imports,
```
import albumentations as A
from fastai.vision.all import *
```
which looks fine except oddly in my version of fastai (2.7.17) there actually is a variable `A` in global scope so this breaks. I'll just create this issue so it can be updated for other people.

**Comment by turleyjm** [comment]
Great thank you for letting my know i have changed this now.
